name: CI

on: [push]

jobs:
  Build and Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.

      - name: Build
        run: cd signer && go mod init main && go build

      - name: Test Pipeline
        run: cd signer && go test -v

